version: '3.8'

services:
  db:
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql-scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: wallet
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  app:
    build: ./wallet
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["python3", "main.py"]
    environment:
      DATABASE_URL: mysql://root:root@db:3306/wallet

volumes:
  db-data:
